### ISSUE TITLE
Double navbar and double footer issue on 404 page

### ISSUE THREAD

**Issue by Bobbbay** [Nexus-Aurora/web-portal#10]
## Issue
Double navbars appear on the 404 page. 

## Tech information
- Operating system: WSL2 Ubuntu 18.04 Windows 19645 release
- Node v14.3.0
- React v16.13.1
- Gatsby CLI version: 2.12.37

## Branch
Develop fb0e84cf419ff285be45e1cf8c47505b11785cfe

## Steps to reproduce 
`git clone https://github.com/Nexus-Aurora/web-portal`
`cd web-portal`
`npm install`
`gatsby develop`
Go to `localhost:8000`
Navigate to an uncreated page (e.x. /assignment)
Press on "view custom 404 page"
There are double navbars and footers, as shown in the following images. 

![image](https://user-images.githubusercontent.com/49123594/84597623-43116500-ae33-11ea-9d8f-71191350b44b.png)
![image](https://user-images.githubusercontent.com/49123594/84597654-6d632280-ae33-11ea-9917-cae0d67b9bf0.png)

**Comment by digitaljohn** [comment]
@Bobbbay If you just visit /404 directly do you get double?

**Comment by Bobbbay** [comment]
> @Bobbbay If you just visit `/404` directly do you get double?

Nope, it's all good on `/404`. Just wondering, have you been able to reproduce?

**Comment by digitaljohn** [comment]
I reproduced... Its just a glitch with Gatsby dev mode in conjunction with the layout plugin I'm using. Will not happen in production... closing...
